### ISSUE TITLE
Minor issues part 1

### ISSUE THREAD

**Issue by emitanaka** [StatSocAus/dicook-award#10]
* Supply a link to the dates section in the criteria section where it mentions the deadline and insert missing be 
"Above should be submitted by completing the application form under Forms before the application deadline"?
* The Judges and Assessors section describes how the assessors are selected but not the judging panel.
* I would add this little paragraph that is in the Prize section to A12 of the application form - to be clear of what will happen to any tutorial upload:
* "All applications of sufficient quality will have their tutorial (if supplied) made available on the website (https://statsocaus.github.io/dicook-award/) with its introduction and link to the tutorial circulated to SSA Vic members and other avenues."
* 
Thanks to Lizzie for these!

**Comment by kevinwang09** [comment]
Thanks @emitanaka. 
I already added the "be". 

And it looks like the assessor part is exactly what is mentioned in #9. 

I added that paragraph just before A12 in https://forms.gle/BeWmazpSnA9Qobxd8.

**Comment by emitanaka** [comment]
Thanks Kevin! I've integrated into A12 since I think it's relevant for that section only
