### ISSUE TITLE
Minor issues part 2

### ISSUE THREAD

**Issue by emitanaka** [StatSocAus/dicook-award#11]
1. The following doesn't flow/make sense. How about changing to "A brief summary of the importance... "

The applicant must submit:

Briefly discuss the importance of the software to statistical practice and discuss the advantages and disadvantages of the new contribution compared to existing implementations. Up to 400 words.
2. I'd recommend changing
make the decision for the winner.
to 
decide the winner.

Thanks to Rheanna!

**Comment by kevinwang09** [comment]
Thanks, it looks like both points were picked up by Damjan in #9.
