### ISSUE TITLE
Add award to SSA main website

### ISSUE THREAD

**Issue by emitanaka** [StatSocAus/dicook-award#12]
As suggested by @dvukcevic

**Comment by kevinwang09** [comment]
That's fair. So who should we contact about making this change, or, should we do this ourselves?

**Comment by dvukcevic** [comment]
For changes to our own part (Vic Branch) of the website, anyone who has 'website editor' privileges can do it.  See [this section on our wiki](https://github.com/StatSocAus/branch-vic/wiki/Tools-and-resources#-ssa-website-event-and-membership-system) for a list of relevant people (hopefully it's up to date...).

For other parts of the website, getting in touch with Marie-Louise is the best bet.

**Comment by emitanaka** [comment]
Added.

**Comment by dvukcevic** [comment]
A minor comment on this (so, I'll just reopen rather than create a new issue):

On the [Di Cook Award](https://www.statsoc.org.au/Di-Cook-Award) just created on the SSA website, the URL at the bottom is not clickable.

**Comment by kevinwang09** [comment]
It looks like I don't have the right access to edit the website, so I will have to leave that with Emi or Damjan: https://github.com/StatSocAus/branch-vic/wiki/Tools-and-resources#-ssa-website-event-and-membership-system

**Comment by dvukcevic** [comment]
I've updated the link.  I also took the opportunity to fix up some of the wording and grammar.  (I hope you don't mind...)
