### ISSUE TITLE
Tutorial for vitae

### ISSUE THREAD

**Issue by emitanaka** [StatSocAus/dicook-award#2]
@mitchelloharawild to write example tutorial for `vitae` (I thought I saw a pull request but can't find it?)

**Comment by mitchelloharawild** [comment]
Haven't forgotten, just slow at writing.
Incomplete PR is here - https://github.com/StatSocAus/dicook-award/pull/4

You may have seen my fork a little while ago and misremembered it as a PR?

**Comment by kevinwang09** [comment]
Thanks Mitch, I wasn't sure who should approve the PR, but have done it anyways. Much appreciate it!

**Comment by mitchelloharawild** [comment]
PR was WIP. I wanted to show an issue with the author field style so started the PR.
