### ISSUE TITLE
Space around logo

### ISSUE THREAD

**Issue by dvukcevic** [StatSocAus/dicook-award#7]
A small design issue...

The logo on the main page is quite 'cramped'.  This makes it harder to read, but also detracts from our branding somewhat.  I suggest putting some more padding around the logo to space it further away from the other elements.

If need be, you might consider setting 'Victorian Branch' across two rows of text.

**Comment by dvukcevic** [comment]
Just to be clear, I am referring to the large logo in the main part of the page, rather than the small one in the navigation bar.

**Comment by kevinwang09** [comment]
Thanks Damjan, I also have the same issues on my browser. Will try to fix that. I think I found those in the SSA Vic Google Drive, will try to experiment with those.

**Comment by kevinwang09** [comment]
I just gave it a crack, happy for any extra suggestions.

**Comment by emitanaka** [comment]
Thanks Kevin! It does look better!
