### ISSUE TITLE
Logo in navigation bar is tiny

### ISSUE THREAD

**Issue by dvukcevic** [StatSocAus/dicook-award#8]
On my browser (and I'm guessing this will be true for most browsers?), the SSA logo in the top-left (in the navigation bar) is so small that it is almost indescribable.

I suggest trying out our 'monogram' logo in there instead.  (That's the one with just the letters 'SSA' in it.)

**Comment by kevinwang09** [comment]
I have fixed this logo the best I could using the monogram. The only issue is that, we don't have a white version of the SSA monogram logo (only black and blue exist in Google Drive). I have to create a new white one to match the theme. I hope that won't break any protocols.

**Comment by dvukcevic** [comment]
Yeah, I think it will be okay to create a white version.
