### ISSUE TITLE
Misc. typos and suggestions

### ISSUE THREAD

**Issue by dvukcevic** [StatSocAus/dicook-award#9]
# [Home](https://github.com/StatSocAus/dicook-award)

See #7 and #8 for previously reported issues about the logos.

## Eligibility

Item 4: "be a SSA member" -> "be an SSA member"

Item 5 (suggestion): "Both individuals and teams are eligible" -> "Individuals or teams are eligible"
*This suggestion is to avoid people interpreting "Both individuals" as referring to two specific individuals and getting confused. Also, it makes it clearer that the entry should be either for an individual or for a team.*

## Criteria

"Briefly discuss" -> "A brief description of"

"endorsing the major software development as student's work." -> "endorsing that the majority of the software development was done by the student(s)."

"The applicant can also optionally submit" -> "The applicant may also optionally submit"

"Above should submitted by" -> "All of these items should be submitted by"

## Judges & Assessors

"make the decision for the winner" -> "decide on the winner"

Explain how the judging panel will be chosen.

## Important Dates

"Opening of the submission" -> "Opening of submissions"
"Close of submission" -> "Close of submissions"

## Prize

"Awardee will" -> "The awardee will"

# [About](https://statsocaus.github.io/dicook-award/about.html)

"This Award aims to" -> "This Award aims to:" (add a colon at the end)

In the enumerated list, capitalise the first letter of each item.

"The use of open-source software (e.g. Python and R) are fast growing among users of programming languages, and are widely used for statistical computing and graphics."
->
"The use of open-source software (e.g. Python and R) is fast growing among users of programming languages, and such software is widely used for statistical computing and graphics."

**Comment by kevinwang09** [comment]
Thanks, @dvukcevic, all of the above were actioned. 

@emitanaka, do we have any info on "Explain how the judging panel will be chosen."? I recall that we are inviting panel members?

**Comment by emitanaka** [comment]
Yes, I intend to approach the new comp + graphics section. We need to make a potential list of assessors too but we will only approach them after the submission are in as we need to make sure we match up the experts with the right application (e.g. Python library needs to be assessed by Python expert). We won't know how many assessors in which area until we have the submissions.

**Comment by kevinwang09** [comment]
So a short paragraph can look like: 

Assessors for this competition will be decided after the initial submission upon consultation with the [Statistical Computing and Visualisation Section of the Statistical Society of Australia](https://www.statsoc.org.au/Statistical-Computing-and-Visualisation-Section). 

BTW, the link is pointing to a blank webpage at the moment. We might want to populate that page with info regarding the Section soon.

**Comment by emitanaka** [comment]
Nice paragraph! I'll try to populate the section with the elected committee soon

**Comment by emitanaka** [comment]
Okay done.
